"""
Artifact Writer — centralized file saver for all generated artifacts.

Handles:
  - QA documents (test cases, checklists, test plans) → qa_docs/
  - Generated Playwright test files               → generated_tests/

Naming convention:
  qa_docs/test_cases_account_section_20260415_143022.md
  qa_docs/checklist_cart_20260415_143022.md
  qa_docs/test_plan_checkout_flow_20260415_143022.md
  generated_tests/test_account_section_functional.py
  generated_tests/test_login_form_smoke.py
"""
from __future__ import annotations
import datetime
import json
import os
import re
from urllib.parse import urlparse

DOCS_DIR  = os.path.join("reports", "qa_docs")
TESTS_DIR = "generated_tests"


# ── Public API ─────────────────────────────────────────────────────────────────

def save_doc(
    content: str,
    doc_type: str,
    scope: str,
    target_url: str,
    also_json: bool = False,
) -> str:
    """
    Save a QA document to qa_docs/.
    Prepends a metadata header. Returns the saved file path.
    Optionally also saves a .json sidecar with metadata.
    """
    _ensure(DOCS_DIR)
    ts         = _ts()
    scope_slug = _slug(scope) if scope else "fullsite"
    type_slug  = _slug(doc_type)
    filename   = os.path.join(DOCS_DIR, f"{type_slug}_{scope_slug}_{ts}.md")

    header = _doc_header(doc_type, scope, target_url)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(header + content)

    if also_json:
        json_path = filename.replace(".md", ".json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "doc_type":   doc_type,
                    "scope":      scope or "full site",
                    "target_url": target_url,
                    "generated":  datetime.datetime.now().isoformat(),
                    "content":    content,
                },
                f,
                ensure_ascii=False,
                indent=2,
            )
        print(f"  JSON sidecar: {json_path}")

    return filename


def save_playwright_test(
    content: str,
    scope: str,
    test_type: str,
    target_url: str,
) -> str:
    """
    Save a generated Playwright .py test file to generated_tests/.
    Prepends a header comment. Returns the saved file path.
    """
    _ensure(TESTS_DIR)
    scope_slug = _slug(scope) if scope else "general"
    type_slug  = _slug(test_type)
    filename   = os.path.join(TESTS_DIR, f"test_{scope_slug}_{type_slug}.py")

    # If a file with the same name already exists, add a timestamp to avoid overwrite
    if os.path.exists(filename):
        filename = filename.replace(".py", f"_{_ts()}.py")

    header = _test_header(scope, test_type, target_url)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(header + content)

    return filename


# ── Helpers ────────────────────────────────────────────────────────────────────

def _ensure(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def _ts() -> str:
    return datetime.datetime.now().strftime("%Y%m%d_%H%M%S")


def _slug(text: str) -> str:
    """Convert a human-readable string to a safe filename fragment."""
    s = re.sub(r"[^\w\s-]", "", text.lower())
    s = re.sub(r"[\s\-]+", "_", s.strip())
    return s[:40]


def _domain(url: str) -> str:
    return urlparse(url).netloc.replace("www.", "") or url


def _doc_header(doc_type: str, scope: str, target_url: str) -> str:
    label = doc_type.replace("_", " ").title()
    ts    = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"# {label}\n\n"
        f"| | |\n|---|---|\n"
        f"| **Site**      | `{_domain(target_url)}` |\n"
        f"| **URL**       | `{target_url}` |\n"
        f"| **Scope**     | {scope or 'Full site'} |\n"
        f"| **Generated** | {ts} |\n\n"
        f"---\n\n"
    )


def _test_header(scope: str, test_type: str, target_url: str) -> str:
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return (
        f"# Generated by QAmachine — Playwright Test\n"
        f"# Site:      {_domain(target_url)}\n"
        f"# URL:       {target_url}\n"
        f"# Scope:     {scope or 'General'}\n"
        f"# Test type: {test_type}\n"
        f"# Generated: {ts}\n"
        f"#\n"
        f"# Run with:  pytest generated_tests/ -v\n\n"
    )
